version: "3.3"

services:
    client:
        build: 
            context: ./frontend
            dockerfile: dockerfile.dev
        image: ant_client_image
        container_name: ant_client
        volumes: 
            - ./frontend:/usr/src/app
        networks: 
            - ant_network
        ports: 
            - 3000:3000
    server:
        build:
            context: .
            dockerfile: dockerfile.dev
        image: ant_server_image
        container_name: ant_server
        volumes:
            - ./:/usr/src/app
        networks:
            - ant_network
        ports: 
            - 5000:5000
        depends_on: 
            - db
        environment:
            - NODE_ENV=dev
            - DB_URL='mongodb://db:27017/ant'
    db:
        image: mongo:latest
        container_name: ant_db
        volumes: 
            - ant_db:/data/db
        networks: 
            - ant_network
        ports: 
            - 27017:27017
volumes: 
    ant_db:
networks: 
    ant_network:
